### PR TITLE
Update Plexus.csv

### PR DESCRIPTION
**Pull request by CPete88**

### CODE REVIEW

**Review by techlore-official — CHANGES_REQUESTED** [review]
Great contribution! If you could please omit apps found on F-Droid that would be great though. Will update it myself after a few days.

**Comment by CPete88** [comment]
Thank you. For future additions, may I please ask for clarification for the following situations?
- For apps offered in F-Droid, do we prioritize the versions found there over micro-G or Aurora?
- I have also seen some developers that offer censored versions of their app in the original Google Play Store and unrestricted version directly from their website (for example, Minds the social media platform)?

**Comment by CPete88** [comment]
Really glad to help make it easier for people to become less-centralized.

**Comment by CPete88** [comment]
Thank you for your patience. I removed all the F-Droid listed apps from the CSV file. The only apps left either came from Google Play only or were the non-FOSS versions of the software that has FOSS-only versions in F-Droid. Please let me know if more alternations are needed.

**Comment by techlore-official** [comment]
Hey there, thanks for the patience. We haven't yet seen an app that differs significantly in its compatibility between the Play Store & its own supplied APK. If this issue comes up then we'll address it. 

Thanks for updating your PR!

**Pull request merged**
